<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1705601107213' stop='1705601125228'>
    <name>PTRF</name>
    <title>PTRF</title>
    <test-cases>
        <test-case start='1705601107213' status='failed' stop='1705601125221'>
            <name>CT02-Prestacoes_de_Contas_Nao_Recebidas_Status_Receber_Pc</name>
            <title>CT02-Prestacoes_de_Contas_Nao_Recebidas_Status_Receber_Pc</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Timed out retrying after 4000ms: Expected to find element: `:nth-child(1) > :nth-child(9) > div > .btn > .svg-inline--fa > path`, but never found it.</message>
                <stack-trace>AssertionError: Timed out retrying after 4000ms: Expected to find element: `:nth-child(1) > :nth-child(9) > div > .btn > .svg-inline--fa > path`, but never found it.
                    at AcompanhamentoPCElementos.eval [as botaoAcoes] (webpack://cypress-ptrf/./cypress/support/Elementos/AcompanhamentoPcElementos.js:8:35)
                    at AcompanhamentoPcPagina.validarPrestacoesContasNaoRecebidasStatusReceberPc (webpack://cypress-ptrf/./cypress/support/Paginas/AcompanhamentoPcPagina.js:29:25)
                    at Context.eval (webpack://cypress-ptrf/./cypress/e2e/PTRF/Acompanhamento_de_PC/CT02-Prestacoes_de_Contas_Nao_Recebidas_Status_Receber_Pc.cy.js:27:21)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>